{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-management.fullname" . }}-postgresql
  labels:
    {{- include "stock-management.database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
    protocol: TCP
  selector:
    {{- include "stock-management.database.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-management.fullname" . }}-backend
  labels:
    {{- include "stock-management.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "stock-management.backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-management.fullname" . }}-frontend
  labels:
    {{- include "stock-management.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "stock-management.frontend.selectorLabels" . | nindent 4 }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-management.fullname" . }}-prometheus
  labels:
    {{- include "stock-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "stock-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
---
{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-management.fullname" . }}-grafana
  labels:
    {{- include "stock-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "stock-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
